export const NAV = {  
  registro: 'registro',
  descargas: 'descargas',
  login: 'login',
  recuperarContrasena: 'recuperar-contrasena',
  codigoRecuperacion: 'codigo-recuperacion',
  nuevaContrasena: 'nueva-contrasena',
  proceso: 'proceso',
  activation: 'activation',
  dashboard: 'dashboard',
  cancelarCfdi: 'cancelar-cfdi',
  generarCfdi: 'generar-cfdi',
  clientesFrecuentes: 'clientes-frecuentes',
  crearProdServ: 'crear-produc-serv',
  espacioTrabajo: 'espacio-trabajo',
  crearCfdi: 'crear-cfdi',
  fullSize: 'full-size',
  perfil: 'perfil',
  saludFiscal: 'salud-fiscal'
};
